modLoader="javafml"
loaderVersion="[41,)"
license="All Rights Reserved"

[[mods]]
modId="love_accessibility"
version="${file.jarVersion}"
displayName="Love Accessibility"
authors="LoveTropics"
credits=""
description='''
'''

[[dependencies.love_accessibility]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.love_accessibility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
